### ISSUE TITLE
Set PasswordMaker as multiprocess compatible (if compatible)

### ISSUE THREAD

**Issue by mailtowim** [emersion/firefox-passwordmaker#28]
On my firefox configuration, PasswordMaker X is blocking firefox from using multi-process (e10s).

https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#add-on-feature-compatibility
https://www.arewee10syet.com/

**Comment by emersion** [comment]
This extension is not compatible with e10s because it uses legacy APIs to support Android. I just updated the listing on addons.mozilla.org to make the addon compatible with Android only.

I created a WebExtension version of this addon here: https://github.com/emersion/passwordmaker

WebExtensions are always compatible with e10s.
